# Generated by Django 4.2.6 on 2023-11-10 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_intrestedclient_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='tenant',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Domain',
        ),
    ]
